# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ubuntu/PycharmProjects/pyqt/UI/mainwindow.ui'
#
# Created: Mon Oct 17 14:30:04 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(737, 536)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.btn_exit = QtGui.QPushButton(self.centralWidget)
        self.btn_exit.setGeometry(QtCore.QRect(640, 440, 80, 23))
        self.btn_exit.setObjectName(_fromUtf8("btn_exit"))
        self.box_vision = QtGui.QGroupBox(self.centralWidget)
        self.box_vision.setGeometry(QtCore.QRect(20, 10, 151, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.box_vision.setPalette(palette)
        self.box_vision.setObjectName(_fromUtf8("box_vision"))
        self.label_light = QtGui.QLabel(self.box_vision)
        self.label_light.setGeometry(QtCore.QRect(10, 30, 52, 15))
        self.label_light.setObjectName(_fromUtf8("label_light"))
        self.label_lightType = QtGui.QLabel(self.box_vision)
        self.label_lightType.setGeometry(QtCore.QRect(20, 50, 52, 15))
        self.label_lightType.setObjectName(_fromUtf8("label_lightType"))
        self.label_stopline = QtGui.QLabel(self.box_vision)
        self.label_stopline.setGeometry(QtCore.QRect(6, 85, 51, 31))
        self.label_stopline.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stopline.setWordWrap(True)
        self.label_stopline.setObjectName(_fromUtf8("label_stopline"))
        self.text_light = QtGui.QLineEdit(self.box_vision)
        self.text_light.setGeometry(QtCore.QRect(70, 30, 70, 23))
        self.text_light.setObjectName(_fromUtf8("text_light"))
        self.text_lightType = QtGui.QLineEdit(self.box_vision)
        self.text_lightType.setGeometry(QtCore.QRect(70, 50, 70, 23))
        self.text_lightType.setObjectName(_fromUtf8("text_lightType"))
        self.text_stopLine = QtGui.QLineEdit(self.box_vision)
        self.text_stopLine.setGeometry(QtCore.QRect(70, 90, 70, 23))
        self.text_stopLine.setObjectName(_fromUtf8("text_stopLine"))
        self.box_crio = QtGui.QGroupBox(self.centralWidget)
        self.box_crio.setGeometry(QtCore.QRect(20, 220, 151, 251))
        self.box_crio.setObjectName(_fromUtf8("box_crio"))
        self.label_ap = QtGui.QLabel(self.box_crio)
        self.label_ap.setGeometry(QtCore.QRect(10, 30, 52, 16))
        self.label_ap.setObjectName(_fromUtf8("label_ap"))
        self.label_bp = QtGui.QLabel(self.box_crio)
        self.label_bp.setGeometry(QtCore.QRect(10, 60, 52, 15))
        self.label_bp.setObjectName(_fromUtf8("label_bp"))
        self.label_speed = QtGui.QLabel(self.box_crio)
        self.label_speed.setGeometry(QtCore.QRect(10, 90, 52, 15))
        self.label_speed.setObjectName(_fromUtf8("label_speed"))
        self.label_steer = QtGui.QLabel(self.box_crio)
        self.label_steer.setGeometry(QtCore.QRect(10, 120, 52, 15))
        self.label_steer.setObjectName(_fromUtf8("label_steer"))
        self.label_yaw = QtGui.QLabel(self.box_crio)
        self.label_yaw.setGeometry(QtCore.QRect(10, 150, 52, 15))
        self.label_yaw.setObjectName(_fromUtf8("label_yaw"))
        self.label_gear = QtGui.QLabel(self.box_crio)
        self.label_gear.setGeometry(QtCore.QRect(10, 175, 52, 20))
        self.label_gear.setObjectName(_fromUtf8("label_gear"))
        self.label_accel = QtGui.QLabel(self.box_crio)
        self.label_accel.setGeometry(QtCore.QRect(10, 205, 52, 20))
        self.label_accel.setObjectName(_fromUtf8("label_accel"))
        self.text_ap = QtGui.QLineEdit(self.box_crio)
        self.text_ap.setGeometry(QtCore.QRect(70, 30, 70, 23))
        self.text_ap.setObjectName(_fromUtf8("text_ap"))
        self.text_bp = QtGui.QLineEdit(self.box_crio)
        self.text_bp.setGeometry(QtCore.QRect(70, 58, 70, 23))
        self.text_bp.setObjectName(_fromUtf8("text_bp"))
        self.text_speed = QtGui.QLineEdit(self.box_crio)
        self.text_speed.setGeometry(QtCore.QRect(70, 87, 70, 23))
        self.text_speed.setObjectName(_fromUtf8("text_speed"))
        self.text_steer = QtGui.QLineEdit(self.box_crio)
        self.text_steer.setGeometry(QtCore.QRect(70, 117, 70, 23))
        self.text_steer.setObjectName(_fromUtf8("text_steer"))
        self.text_yaw = QtGui.QLineEdit(self.box_crio)
        self.text_yaw.setGeometry(QtCore.QRect(70, 146, 70, 23))
        self.text_yaw.setObjectName(_fromUtf8("text_yaw"))
        self.text_gear = QtGui.QLineEdit(self.box_crio)
        self.text_gear.setGeometry(QtCore.QRect(70, 176, 70, 23))
        self.text_gear.setObjectName(_fromUtf8("text_gear"))
        self.text_accel = QtGui.QLineEdit(self.box_crio)
        self.text_accel.setGeometry(QtCore.QRect(70, 206, 70, 23))
        self.text_accel.setObjectName(_fromUtf8("text_accel"))
        self.box_planner = QtGui.QGroupBox(self.centralWidget)
        self.box_planner.setGeometry(QtCore.QRect(190, 10, 231, 461))
        self.box_planner.setObjectName(_fromUtf8("box_planner"))
        self.label_mission = QtGui.QLabel(self.box_planner)
        self.label_mission.setGeometry(QtCore.QRect(10, 30, 51, 31))
        self.label_mission.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mission.setWordWrap(True)
        self.label_mission.setObjectName(_fromUtf8("label_mission"))
        self.progressbar_missionNum = QtGui.QProgressBar(self.box_planner)
        self.progressbar_missionNum.setGeometry(QtCore.QRect(80, 30, 118, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(113, 198, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 198, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 8, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.progressbar_missionNum.setPalette(palette)
        self.progressbar_missionNum.setMinimum(0)
        self.progressbar_missionNum.setMaximum(8)
        self.progressbar_missionNum.setProperty("value", 1)
        self.progressbar_missionNum.setObjectName(_fromUtf8("progressbar_missionNum"))
        self.box_lidar = QtGui.QGroupBox(self.centralWidget)
        self.box_lidar.setGeometry(QtCore.QRect(20, 130, 151, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.box_lidar.setPalette(palette)
        self.box_lidar.setObjectName(_fromUtf8("box_lidar"))
        self.label_lidarX = QtGui.QLabel(self.box_lidar)
        self.label_lidarX.setGeometry(QtCore.QRect(12, 31, 52, 15))
        self.label_lidarX.setObjectName(_fromUtf8("label_lidarX"))
        self.label_lidarY = QtGui.QLabel(self.box_lidar)
        self.label_lidarY.setGeometry(QtCore.QRect(12, 51, 52, 15))
        self.label_lidarY.setObjectName(_fromUtf8("label_lidarY"))
        self.text_lidarX = QtGui.QLineEdit(self.box_lidar)
        self.text_lidarX.setGeometry(QtCore.QRect(70, 30, 70, 23))
        self.text_lidarX.setObjectName(_fromUtf8("text_lidarX"))
        self.text_lidarY = QtGui.QLineEdit(self.box_lidar)
        self.text_lidarY.setGeometry(QtCore.QRect(70, 50, 70, 23))
        self.text_lidarY.setObjectName(_fromUtf8("text_lidarY"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 737, 20))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.btn_exit.setText(_translate("MainWindow", "Exit", None))
        self.box_vision.setTitle(_translate("MainWindow", "Vision", None))
        self.label_light.setText(_translate("MainWindow", "Light ", None))
        self.label_lightType.setText(_translate("MainWindow", "Type", None))
        self.label_stopline.setText(_translate("MainWindow", "Stop line", None))
        self.box_crio.setTitle(_translate("MainWindow", "C-Rio", None))
        self.label_ap.setText(_translate("MainWindow", "ap", None))
        self.label_bp.setText(_translate("MainWindow", "bp", None))
        self.label_speed.setText(_translate("MainWindow", "speed", None))
        self.label_steer.setText(_translate("MainWindow", "steer", None))
        self.label_yaw.setText(_translate("MainWindow", "yawrate", None))
        self.label_gear.setText(_translate("MainWindow", "gear", None))
        self.label_accel.setText(_translate("MainWindow", "accel", None))
        self.box_planner.setTitle(_translate("MainWindow", "Mission Planner", None))
        self.label_mission.setText(_translate("MainWindow", "Mission number", None))
        self.progressbar_missionNum.setFormat(_translate("MainWindow", "%v", None))
        self.box_lidar.setTitle(_translate("MainWindow", "Lidar", None))
        self.label_lidarX.setText(_translate("MainWindow", "x", None))
        self.label_lidarY.setText(_translate("MainWindow", "y", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

